// Generated by gencpp from file beginner_tutorials/ForceData.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_FORCEDATA_H
#define BEGINNER_TUTORIALS_MESSAGE_FORCEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ForceData_
{
  typedef ForceData_<ContainerAllocator> Type;

  ForceData_()
    : id(0)
    , data()  {
      data.assign(0);
  }
  ForceData_(const ContainerAllocator& _alloc)
    : id(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef boost::array<int16_t, 8>  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::beginner_tutorials::ForceData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ForceData_<ContainerAllocator> const> ConstPtr;

}; // struct ForceData_

typedef ::beginner_tutorials::ForceData_<std::allocator<void> > ForceData;

typedef boost::shared_ptr< ::beginner_tutorials::ForceData > ForceDataPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ForceData const> ForceDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ForceData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ForceData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/robot/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ForceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ForceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ForceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ForceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ForceData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ForceData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b61d0924a09e3316ba5fea2e1ca8c6f";
  }

  static const char* value(const ::beginner_tutorials::ForceData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b61d0924a09e331ULL;
  static const uint64_t static_value2 = 0x6ba5fea2e1ca8c6fULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ForceData";
  }

  static const char* value(const ::beginner_tutorials::ForceData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int16[8] data\n\
";
  }

  static const char* value(const ::beginner_tutorials::ForceData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ForceData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ForceData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ForceData_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_FORCEDATA_H
