// Generated by gencpp from file darknet_ros_msgs/TargetPoints.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_TARGETPOINTS_H
#define DARKNET_ROS_MSGS_MESSAGE_TARGETPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <darknet_ros_msgs/TargetPoint.h>

namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct TargetPoints_
{
  typedef TargetPoints_<ContainerAllocator> Type;

  TargetPoints_()
    : header()
    , image_header()
    , target_points()  {
    }
  TargetPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , target_points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >::other >  _target_points_type;
  _target_points_type target_points;




  typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> const> ConstPtr;

}; // struct TargetPoints_

typedef ::darknet_ros_msgs::TargetPoints_<std::allocator<void> > TargetPoints;

typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoints > TargetPointsPtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoints const> TargetPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'darknet_ros_msgs': ['/home/robot/catkin_ws/src/darknet_ros/darknet_ros_msgs/msg', '/home/robot/catkin_ws/devel/share/darknet_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4425c9132ffe8af00c898f69b716663e";
  }

  static const char* value(const ::darknet_ros_msgs::TargetPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4425c9132ffe8af0ULL;
  static const uint64_t static_value2 = 0x0c898f69b716663eULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/TargetPoints";
  }

  static const char* value(const ::darknet_ros_msgs::TargetPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Header image_header\n\
TargetPoint[] target_points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: darknet_ros_msgs/TargetPoint\n\
string Class\n\
float64 probability\n\
float64 camera_x\n\
float64 camera_y\n\
float64 camera_z\n\
";
  }

  static const char* value(const ::darknet_ros_msgs::TargetPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.target_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::TargetPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::TargetPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "target_points[]" << std::endl;
    for (size_t i = 0; i < v.target_points.size(); ++i)
    {
      s << indent << "  target_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.target_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_TARGETPOINTS_H
