// Generated by gencpp from file darknet_ros_msgs/TargetPoint.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_TARGETPOINT_H
#define DARKNET_ROS_MSGS_MESSAGE_TARGETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct TargetPoint_
{
  typedef TargetPoint_<ContainerAllocator> Type;

  TargetPoint_()
    : Class()
    , probability(0.0)
    , camera_x(0.0)
    , camera_y(0.0)
    , camera_z(0.0)  {
    }
  TargetPoint_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , probability(0.0)
    , camera_x(0.0)
    , camera_y(0.0)
    , camera_z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef double _probability_type;
  _probability_type probability;

   typedef double _camera_x_type;
  _camera_x_type camera_x;

   typedef double _camera_y_type;
  _camera_y_type camera_y;

   typedef double _camera_z_type;
  _camera_z_type camera_z;




  typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> const> ConstPtr;

}; // struct TargetPoint_

typedef ::darknet_ros_msgs::TargetPoint_<std::allocator<void> > TargetPoint;

typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoint > TargetPointPtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::TargetPoint const> TargetPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'darknet_ros_msgs': ['/home/robot/catkin_ws/src/darknet_ros/darknet_ros_msgs/msg', '/home/robot/catkin_ws/devel/share/darknet_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35dbeb86b706cfd5d35e4c142abe1f81";
  }

  static const char* value(const ::darknet_ros_msgs::TargetPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35dbeb86b706cfd5ULL;
  static const uint64_t static_value2 = 0xd35e4c142abe1f81ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/TargetPoint";
  }

  static const char* value(const ::darknet_ros_msgs::TargetPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n\
float64 probability\n\
float64 camera_x\n\
float64 camera_y\n\
float64 camera_z\n\
";
  }

  static const char* value(const ::darknet_ros_msgs::TargetPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.probability);
      stream.next(m.camera_x);
      stream.next(m.camera_y);
      stream.next(m.camera_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::TargetPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::TargetPoint_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "camera_x: ";
    Printer<double>::stream(s, indent + "  ", v.camera_x);
    s << indent << "camera_y: ";
    Printer<double>::stream(s, indent + "  ", v.camera_y);
    s << indent << "camera_z: ";
    Printer<double>::stream(s, indent + "  ", v.camera_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_TARGETPOINT_H
