// Generated by gencpp from file kinect_detect_msgs/ObjectIDs.msg
// DO NOT EDIT!


#ifndef KINECT_DETECT_MSGS_MESSAGE_OBJECTIDS_H
#define KINECT_DETECT_MSGS_MESSAGE_OBJECTIDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinect_detect_msgs
{
template <class ContainerAllocator>
struct ObjectIDs_
{
  typedef ObjectIDs_<ContainerAllocator> Type;

  ObjectIDs_()
    : object_ids()  {
    }
  ObjectIDs_(const ContainerAllocator& _alloc)
    : object_ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _object_ids_type;
  _object_ids_type object_ids;




  typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectIDs_

typedef ::kinect_detect_msgs::ObjectIDs_<std::allocator<void> > ObjectIDs;

typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectIDs > ObjectIDsPtr;
typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectIDs const> ObjectIDsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect_detect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'kinect_detect_msgs': ['/home/robot/catkin_ws/src/kinect_detect_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51b8c1ab69cd630e4f6eaee2d22fc8d0";
  }

  static const char* value(const ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51b8c1ab69cd630eULL;
  static const uint64_t static_value2 = 0x4f6eaee2d22fc8d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_detect_msgs/ObjectIDs";
  }

  static const char* value(const ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] object_ids\n\
";
  }

  static const char* value(const ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectIDs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect_detect_msgs::ObjectIDs_<ContainerAllocator>& v)
  {
    s << indent << "object_ids[]" << std::endl;
    for (size_t i = 0; i < v.object_ids.size(); ++i)
    {
      s << indent << "  object_ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.object_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_DETECT_MSGS_MESSAGE_OBJECTIDS_H
