// Generated by gencpp from file kinect_detect_msgs/ObjectPoses.msg
// DO NOT EDIT!


#ifndef KINECT_DETECT_MSGS_MESSAGE_OBJECTPOSES_H
#define KINECT_DETECT_MSGS_MESSAGE_OBJECTPOSES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kinect_detect_msgs/ObjectPose.h>

namespace kinect_detect_msgs
{
template <class ContainerAllocator>
struct ObjectPoses_
{
  typedef ObjectPoses_<ContainerAllocator> Type;

  ObjectPoses_()
    : object_poses()  {
    }
  ObjectPoses_(const ContainerAllocator& _alloc)
    : object_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kinect_detect_msgs::ObjectPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::kinect_detect_msgs::ObjectPose_<ContainerAllocator> >::other >  _object_poses_type;
  _object_poses_type object_poses;




  typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPoses_

typedef ::kinect_detect_msgs::ObjectPoses_<std::allocator<void> > ObjectPoses;

typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectPoses > ObjectPosesPtr;
typedef boost::shared_ptr< ::kinect_detect_msgs::ObjectPoses const> ObjectPosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect_detect_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'kinect_detect_msgs': ['/home/robot/catkin_ws/src/kinect_detect_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dea7b0d2a30c999d7206bf1518da1588";
  }

  static const char* value(const ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdea7b0d2a30c999dULL;
  static const uint64_t static_value2 = 0x7206bf1518da1588ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_detect_msgs/ObjectPoses";
  }

  static const char* value(const ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ObjectPose[] object_poses\n\
\n\
================================================================================\n\
MSG: kinect_detect_msgs/ObjectPose\n\
uint8 class_id\n\
float64 confidence\n\
uint32[4] rect\n\
float64[3] center\n\
float64[4] quaternation\n\
";
  }

  static const char* value(const ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect_detect_msgs::ObjectPoses_<ContainerAllocator>& v)
  {
    s << indent << "object_poses[]" << std::endl;
    for (size_t i = 0; i < v.object_poses.size(); ++i)
    {
      s << indent << "  object_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kinect_detect_msgs::ObjectPose_<ContainerAllocator> >::stream(s, indent + "    ", v.object_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_DETECT_MSGS_MESSAGE_OBJECTPOSES_H
